#configuration options here https://jekyllrb.com/docs/configuration/options/

url: "https://grognard.ca" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Grognard Digital Solutions" # the name of your site, e.g. ACME Corp.

# Change output location of built site
destination: "grognard.ca"

timezone: "America/Toronto"


# Add defaults to front matter
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope: # defaults that only applies to jekyll files in the '_articles' files
      path: "_articles"
    values:
      layout: "default"